name: video_player_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  video_player: 2.8.1
  firebase_storage: ^11.5.6
  aveoauth: 
    git: 
      url: https://gitlab+deploy-token-2:ioxmzyK_YCZk3GFyyg6e@gitlab.aveosoft.com/aveo-mobile-products/aveoauth.git
      ref: master
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/image/

